version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/okf"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/samples/discovery"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/samples/enrichment/src"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/toolbox/enrichment"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/toolbox/mdcode"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
